# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xToCwP_jVzdjbWJdeJ9tdfx54ueCL2o5
"""

sentence = input()

exit_words = ['esc','quit','stop','exit']

def lowercase(sent):
    return sentence.lower()

x = lowercase(sentence)

x

def uppercase(sent):
  return sent.upper()

uppercase("lachi-molala")

while True:
    x = input("Enter a string: ")  # Get input string
    if x in exit_words:
        break  # Exit if the input is in exit words

    choice = input("Give 1 or 2 option: ")  # Ask for user choice

    if choice == "1":
        print(x.lower())  # Convert to lowercase
    elif choice == "2":
        print(x.upper())  # Convert to uppercase
    else:
        print("Invalid choice")

