# -*- coding: utf-8 -*-
"""DAY-30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbp4VplQTGk62akDzJiStwlLk647VDdN
"""

from textblob import TextBlob

def analyze_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity

    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

if __name__ == "__main__":
    text = input("Enter text for sentiment analysis: ")
    sentiment = analyze_sentiment(text)
    print(f"The sentiment of the text is: {sentiment}")