# -*- coding: utf-8 -*-
"""day-28

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5R9T2iCpxVwP_jMwd1_bPZwjoBcO9Ca
"""

#Write a Python program to perform Named Entity Recognition (NER) on a given text using SpaCy. Print the entities and their types.
import spacy

# Load the English NLP model
nlp = spacy.load("en_core_web_sm")

def perform_ner(text):
    # Process the text
    doc = nlp(text)

    # Print named entities and their labels
    print("Entities and their types:")
    for ent in doc.ents:
        print(f"{ent.text}: {ent.label_}")

# Example usage
text = "Apple was founded by Steve Jobs in Cupertino, California."
perform_ner(text)

