# -*- coding: utf-8 -*-
"""day-22

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5R9T2iCpxVwP_jMwd1_bPZwjoBcO9Ca
"""

#Write a Python script to perform part-of-speech tagging on the sentence: 'NLP is amazing and fun to learn.' using SpaCy.

import spacy

# Load the English NLP model
nlp = spacy.load("en_core_web_sm")

# Input sentence
sentence = "NLP is amazing and fun to learn."

# Process the sentence
doc = nlp(sentence)

# Print the POS tagging
print("Token\tPOS Tag")
print("----------------")
for token in doc:
    print(f"{token.text}\t{token.pos_}")

