# -*- coding: utf-8 -*-
"""DAY-32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbp4VplQTGk62akDzJiStwlLk647VDdN
"""

import re
from collections import Counter

def load_text(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read().lower()

def tokenize(text):
    return re.findall(r'\b\w+\b', text)

def compute_tf(tokens):
    return Counter(tokens)

def main():
    file_path = 'sample.txt'  # Change this to your file path
    text = load_text(file_path)
    tokens = tokenize(text)
    tf = compute_tf(tokens)

    print("Top 5 most frequent tokens:")
    for token, freq in tf.most_common(5):
        print(f"{token}: {freq}")

if __name__ == "__main__":
    main()